# use vim as the visual editor
export VISUAL='vim'
export EDITOR=$VISUAL

# Path to my oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

BASE="$HOME/.zsh"
for file in "$BASE/"*.zsh; do
  source "$file"
done

ZSH_THEME="robbyrussell"
test -f $HOME/.oh-my-zsh/custom/themes/elena.zsh-theme && ZSH_THEME="elena"

if [[ "$CODESPACES" = "true" ]]; then
  if [ -z "$(git config --get core.editor)" ] && [ -z "${GIT_EDITOR}" ]; then
    if  [ "${TERM_PROGRAM}" = "vscode" ]; then
        if [[ -n $(command -v code-insiders) &&  -z $(command -v code) ]]; then
            export GIT_EDITOR="code-insiders --wait"
        else
            export GIT_EDITOR="code --wait"
        fi
    fi
  fi
fi

# Fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# If rbenv is installed, ensure that it's in the path and initialised
if [ -x "$(command -v rbenv)" ]; then
  echo $PATH | grep rbenv >/dev/null || export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

source $ZSH/oh-my-zsh.sh
