# use vim as the visual editor
export VISUAL='vim'
export EDITOR=$VISUAL

# Path to my oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

BASE="$HOME/.zsh"
for file in "$BASE/$1"*.zsh; do
  source "$file"
done

ZSH_THEME="robbyrussell"
test -f $HOME/.oh-my-zsh/custom/themes/elena.zsh-theme && ZSH_THEME="elena"

# Chruby
source $(brew --prefix)/opt/chruby/share/chruby/chruby.sh
source $(brew --prefix)/opt/chruby/share/chruby/auto.sh
chruby ruby-3.1.0

. $HOME/.zshenv

source $ZSH/oh-my-zsh.sh
