# use vim as the visual editor
export VISUAL='vim'
export EDITOR=$VISUAL

# Path to my oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

BASE="$HOME/.zsh"
for file in "$BASE/$1"*.zsh; do
  source "$file"
done

ZSH_THEME="robbyrussell"
test -f $HOME/.oh-my-zsh/custom/themes/elena.zsh-theme && ZSH_THEME="elena"

# If rbenv is installed, ensure that it's in the path and initialised
if [ -x "$(command -v rbenv)" ]; then
  echo $PATH | grep rbenv >/dev/null || export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

. $HOME/.zshenv

source $ZSH/oh-my-zsh.sh
